collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4730547
  brandStrength: 0.4806071
  lightness: 0.7836887
  brandColors:
    - '#0D2A52'
    - '#BEBEBE'
    - '#FFFFFF'
    - '#546D8F'
  rhythmicContrast: 0.6437251
typography_spectrum: 0.4114671
layout_spectrum: 1
name: Kevin Edwards
