layout_spectrum: 1
color:
  saturation: 0.4730547
  lightness: 0.7836887
  brandStrength: 0.7160791
  rhythmicContrast: 0.6437251
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.4381647
name: Kevin Edwards
